import type { NextPage } from 'next'
import Head from 'next/head'
import { ColorModeScript } from '@chakra-ui/react'
import theme from '../theme';
import ItemDetail from '../feature/itemDetail';

const Detail: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Information</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <main >
       <ItemDetail/>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Detail;
